server:
  port: 8888

spring:
  application:
    name: config-server-git

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/yagmurbarank/social-media-config-server"
          default-label: "main"
          skip-ssl-validation: true
          username: "yagmurbarank"
          password: ${GIT_KEY}
