server:
  port: 9091

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: yagmur
      password: root
      database: UserProfileDB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
